Removing nodesecurity CodeClimate engine
Due to
Error: npm-shrinkwrap.json is required for offline mode
    at module.exports (/app/lib/check.js:129:23)
    at Object.onCommand [as command] (/app/lib/commands/check.js:22:3)
    at doCb (/app/node_modules/subcommand/index.js:39:19)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3